---
wordpress_host: 192.168.98.117

wp_title: wordpress

wp_admin_name: admin
wp_admin_email: root@wordpress.box
wp_admin_password: changeme

dbname: wordpress
dbuser: wordpress
dbpassword: changeme
dbport: 3306

wordpress_installs:   # see - https://galaxy.ansible.com/oefenweb/wordpress
  - name: '{{ wp_title }}'
    dbname: '{{ dbname }}'
    dbuser: '{{ dbuser }}'
    dbpass: '{{ dbpassword }}'
    dbhost: localhost
    path: '/var/www/{{ wp_title }}'
    url: 'http://{{ wordpress_host }}'
    title: '{{ wp_title }}'
    admin_name: '{{ wp_admin_name }}'
    admin_email: '{{ wp_admin_email }}'
    admin_password: '{{ wp_admin_password }}'
    themes:
      - name: twentytwelve
        activate: true
    plugins: []
    users: {}
    options: []
    queries: []
